const { Safe } = require('../lib/index');

const new_safe = () => {
  // This requires the safe-nodejs lib to be built with scl-mock feature
  let safe = new Safe();
  const auth_credentials = "bAEAAAAEJEFCFUAAAAAAAAAAAAAAQAAAA6O7E4DY4ISQTQOEEMAODP5TIR5TDYLGUVHD2KX5O6ZRQ2AM5C5KIJJ4ZC7ZMIIYXPUMH7Q26WEUUOBXYWMBMWJAM2XOQZHN4N7FIOPZCK7KXARS7JIICAA2D6SXWBNAXAEAAAAEEU6MRP4WEEMLX2GD7YNPLCKKHA34LGAWLEQGNLXIMTW6G7SUHH4RFPVLQIZPUUEBAANB7JL3AWQLQCAAAACJAO5G3L5XWJQLUIXWV7PFT3KBQEEU5NXSPECMKJYNCT7E24QEGSCO37RR5EAN3NUJ7M5SQGCBSV5WBUMBFXJI4CTCKSTOAWYHBLEBO6VXF3XCMEPGYRUVVYWZNU3YFI6UQLHQXU5NAHG64ORJ5YDDLC3OVUI3DSRPMXL5QHXETBSYOFNCKE7T6I3MWAFOS7HLKJRRH7QFFLP7753YOO5IFXUILLM2LPSG6XP5ST6K2SQDQFESPXWCGNDSAE6QJL4AQAAAAAAAAAAAAAAAAA7YAAAA6ALRIM5LDRGZJ26ZW5KA7HB3FTYLLRQYUVTKSJAUELCBMNKYDTXGI2SMDUAAAAAAAAAFPAMIIJ4XX2EJNRZAFGX4HXSMIAAAAAAAAAAAAAAA";
  safe.connect("net.maidsafe.safe-nodejs", auth_credentials);
  return safe;
};

module.exports = {
  new_safe
};
